name: recycling_points
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  bootstrap_icons: ^1.13.1+1
  flutter:
    sdk: flutter
  camera: ^0.11.4        # Para abrir la cámara nativa del celular
  hand_landmarker: ^2.2.0  # Detección de manos con MediaPipe
  http: ^1.1.0           # Para enviar la foto mediante POST a AdonisJS
  path: ^1.8.3           # Para manejar las rutas de los archivos de imagen
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2   #para obtener la ubicación del usuario
  image_picker: ^1.0.4
  webview_flutter: ^4.10.0
  web: ^1.1.0
  webview_flutter_android: ^4.13.0
  webview_flutter_wkwebview: ^3.26.0
  webview_flutter_web: ^0.2.3+4
  socket_io_client: ^3.1.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/imagen_de_fondo.png
